### ISSUE TITLE
Videos on homepage won't render

### ISSUE THREAD

**Issue by mcclowes** [the-business-of-cities/tboc-site-marketing#21]
`Section`s include the option to add a video by URL. This is reportedly not working (unverified).

Either:
- Section logic results in videos not rendering
- There's an issue with the (use of) the react video player

**Comment by mcclowes** [comment]
https://github.com/the-business-of-cities/tboc-site-components/pull/22

**Comment by AaronBP** [comment]
This one should be resolved
